name: stacked_generator
description: Stacked Generator is a package dedicated to reduce the boilerplate required to setup a stacked application
version: 2.0.0

homepage: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_generator

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  build: ^3.0.0
  path: ^1.9.1
  recase: ^4.1.0
  source_gen: ^3.0.0
  meta: ^1.16.0
  logger: ^2.6.0
  stacked_shared: ^1.4.2

  # Removing this will cause issues when publish the package
  analyzer: ^8.0.0
  dart_style: ^3.1.0
  code_builder: ^4.10.1
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  xdg_directories: ^1.1.0

dev_dependencies:
  build_runner: ^2.5.4
  test: ^1.26.2
  build_test: ^3.2.1
  flutter_lints: ^6.0.0
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6
